### ISSUE TITLE
Icon for "Send to bluetooth recipient..." in Thunar Missing

### ISSUE THREAD

**Issue by bongochong** [sixsixfive/ivy#4]
See: ![screenshot - 01142015 - 06 38 22 pm](https://cloud.githubusercontent.com/assets/10101120/5750043/f72fa94a-9c1c-11e4-90eb-238774a6aa76.png)

Also, not sure if the "Applications" menu icon is intended to have a question mark or not:
![screenshot - 01142015 - 06 38 56 pm](https://cloud.githubusercontent.com/assets/10101120/5750048/1289e016-9c1d-11e4-8acc-40d8f69c21ec.png)

**Comment by bongochong** [comment]
P.S. Big improvements lately. The aesthetic of this icon set is fabulous.

**Comment by sixsixfive** [comment]
sadly, there is currently no icon included for the send file action, because i didn't had a good idea yet :( eg: everytime i draw something it gets too complex to display it in smaller sizes...

**Comment by bongochong** [comment]
I'm not too great with visual art, but maybe borrow the icon from the shimmerproject xubuntu icon them? it's pretty standard.

**Comment by sixsixfive** [comment]
there should now an icon for this action if you checkout and build the latest git, but it's still missing some sizes(22,24 & 32)

**Comment by sixsixfive** [comment]
see also: http://googledrive.com/host/0B_2_dsXrefR-Q1NNdTA1MXRiUnc

**Comment by bongochong** [comment]
beautiful! i have finally replaced elementary xfce with ivy. thanks for all the work so far. loving it.
