### ISSUE TITLE
Wrong icons in SoundConverter

### ISSUE THREAD

**Issue by nerdouille** [sixsixfive/ivy#5]
Hi,

This is a very minor thing that only seems to affect SoundConverter:

http://s17.postimg.org/fiz99bdi7/issue1.png
http://s22.postimg.org/5q1mfjdj5/issue2.png

Most of the icons are fine except the ones for Add file, Select all and Clear List. Any ideas? Thanks

**Comment by sixsixfive** [comment]
the select all icon is correct(https://github.com/sixsixfive/ivy/blob/master/ivy-dev/48/pool/select-all.svg its just currently not downscaled to other sizes so its a bit blurry)

@ add file/Clear List

this comes from sound converter eg(Add File) [the menu entry will load image2](https://github.com/kassoulet/soundconverter/blob/master/data/soundconverter.glade#L2136) and image2 is defined at line [472](https://github.com/kassoulet/soundconverter/blob/master/data/soundconverter.glade#L472) as gtk-dialog-warning

**Comment by nerdouille** [comment]
Ok then, thought it had something to do with ivy, thanks !
