### ISSUE TITLE
/bin/sh non-compliant build.sh

### ISSUE THREAD

**Issue by jcadduono** [sixsixfive/Ivy#7]
might wanna have users execute build.sh in a shell other than /bin/sh, some people will end up with bad substitution errors etc. since build.sh has a few areas in it that aren't /bin/sh compliant so it seems.
i was confused at first, but changed the top line in build.sh to #!/bin/bash and it executed perfectly.

i guess this issue is dependent on the distro you use, since some might just be linking /bin/sh to /bin/bash in the first place, avoiding this problem altogether.

easy solution for now i suppose is just to say in readme "if it doesn't work, try bash build.sh instead"

awesome icons by the way, i use them to introduce new folks to linux desktops without them running away saying it's ugly.

**Comment by sixsixfive** [comment]
hm must have added this in one of the latest updates anyway it should be working again with pure posix shells like dash & co
